verbose: true
instrumentation:
    root: ./test/mock-component
    default-excludes: true
    excludes:
      - "**/*.marko.js"
    embed-source: true
    variable: __coverage__
    compact: false
    preserve-comments: false
    complete-copy: true
    save-baseline: false
    baseline-file: ./.coverage/coverage-baseline.json
    include-all-sources: true,
    preload-sources: true
reporting:
    print: summary
    reports:
        - json
        - html
    dir: ./.coverage
    watermarks:
        statements: [50, 70]
        lines: [50, 70]
        functions: [40, 60]
        branches: [35, 50]
    report-config:
        json: {file: coverage-final.json}
hooks:
    hook-run-in-context: true
    post-require-hook: null
    handle-sigint: true
check:
    global:
        statements: 70
        lines: 70
        functions: 60
        branches: 50
        excludes: []
    each:
        statements: 0
        lines: 0
        branches: 0
        functions: 0
        excludes: []
